<?= $this->messenger( $this->message ); ?>
<?php foreach( $this->project as $project ) { break; } 
      $progressPoints = explode( '|' , $project->progressPoints ); ?>

<section class="part red">
    <div class="area">
        <h2 class="white-text">Project: <?= $project->name ?></h2>
    </div>
</section>

<section class="part">
    <div class="area">
        <br />
        <h4>Project info</h4>
        <hr />
        <p class="indent justify big dark-grey-text margin"><?= $project->desc ?></p>
        <p class="big red-text margin"><a target="_blank" href="http://dev.sleanded.com/<?= $this->urlParser( $project->name ) ?>">View page</a></p>
        <h4>Progress</h4>
        <hr />
        <div class="progress-bar stripped" data-percent="<?= ( $project->progress + 1 ) / ( count( $progressPoints ) + 1 ) * 100 ?>%">
            <div><label>Project progress</label></div>    
        </div>
        <ul class="progress-menu">
            <?php foreach( $progressPoints as $index=>$point ) : ?>
                <?php if( $index < $project->progress ) : ?>
                    <li class="big done"><i class="fa-li fa fa-check-square"></i><?= $point ?></li>
                <?php elseif( $index == $project->progress ) : ?>
                    <li class="big bold processing"><i class="fa-li fa fa-spinner fa-spin"></i><?= $point ?></li>
                <?php else : ?>
                    <li class="big waiting"><i class="fa-li fa fa-square"></i><?= $point ?></li>
                <?php endif; ?>
            <?php endforeach; ?>
            <?php if( $project->progress == count( $progressPoints ) ) : ?>
                    <li class="big done"><i class="fa-li fa fa-check-square"></i>Done!</li>
            <?php else : ?>
                    <li class="big waiting"><i class="fa-li fa fa-square"></i>Done!</li>
            <?php endif;?>
        </ul>
        <h4>Deadline</h4>
        <hr />
        <h3 class="center red-text"><?= $this->date( $project->deadline )?></h3>
    </div>
</section>