<?php echo $this->messenger( $this->message ); ?>

<section class="part red">
    <div class="area">
        <h2 class="white-text">Contact us</h2>
    </div>
</section>
<section class="part white">
    <div class="area">
        <h3 class="red-text">Useful contact information</h3>
        <table class="table-basic" width="100%;">
            <tr>
                <th width="50%">E-mail</th>
                <td>info@sleanded.com</td>
            </tr>
            <tr>
                <th width="50%">Phone</th>
                <td>+420 720 468 227, +420 720 468 227</td>
            </tr>  
            <tr>
                <th width="50%">Identification number</th>
                <td>asdfasdf</td>
            </tr>     
            <tr>
                <th width="50%">Address</th>
                <td>Český Těšín, ČR</td>
            </tr>         
        </table>
    </div>
</section>
<section class="part red">
    <div class="area">
        <h3 class="white-text">Contact us online!</h3>
        <p class="big margin center white-text">It's easy! Just fill out this form and hit the send button!</p>
        <?php $form = $this->contactForm;
              $form->prepare();
              echo $this->form()->openTag($form); ?>
        
            <?php echo $this->formElement( $form->get('name') ) .  
                       $this->formElement( $form->get('email') ) . 
                       $this->formElement( $form->get('text') ) .
                       $this->formButton( $form->get('submit') , "send" ); ?>
        
        <?php echo $this->form()->closeTag(); ?>
    </div>
</section>