<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Sleanded')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/hover.min.css'))
                        ->prependStylesheet($this->basePath('css/admin.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/masonry.pkgd.min.js'), 'text/javascript')
            ->prependFile($this->basePath('js/admin.js'), 'text/javascript')
            ->prependFile($this->basePath('js/jquery.imageScroll.min.js'), 'text/javascript')
            ->prependFile($this->basePath('js/jquery.nicescroll.min.js'), 'text/javascript')
            ->prependFile('http://code.jquery.com/jquery.min.js', 'text/javascript')
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>   
        <div class="page">
            <header>
                <a href="<?php echo $this->basePath("admin"); ?>"><div class="logo">Admin</div></a>
                <nav>
                    <a class="clear"></a>
                    <div>
                        <a>reference</a>
                        <nav>
                            <a>list</a>
                            <a>add new</a>
                        </nav>
                    </div>
                    <div>
                        <a>blog</a>
                        <nav>
                            <a>all articles</a>
                            <a>write article</a>
                        </nav>
                    </div>
                    <a href="<?php echo $this->basePath("admin/messages"); ?>">messages</a>
                    <div>
                        <a href="<?php echo $this->basePath("admin/users"); ?>">users</a>
                        <nav>
                            <a href="<?php echo $this->basePath("admin/users"); ?>">list</a>
                            <a href="<?php echo $this->basePath("admin/users/add"); ?>">add new</a>
                        </nav>
                    </div>
                    <a class="clear"></a>
                    <div>
                        <a>projects</a>
                        <nav>
                            <a>list of projects</a>
                            <a>add new</a>
                        </nav>
                    </div>
                    <a>idea sheet</a>
                    <div>
                        <a>statistics</a>
                        <nav>
                            <a>visitors</a>
                            <a>newsletter</a>
                        </nav>
                    </div>
                    <a class="clear"></a>
                    <a>profile</a>
                    <a href="<?php echo $this->basePath("admin/login"); ?>">logout</a>
                    <a class="clear"></a>
                    <a href="<?php echo $this->basePath(); ?>">site</a>
                </nav>
            </header>

            <div id="content">
                <div id="container">
                    <?php echo $this->content; ?>
                </div>
            </div>

            <footer>
            
            </footer>

            <?php echo $this->inlineScript() ?>
        </div>
    </body>
</html>
