<div class="login-area">
    <div class="tile no-hover">
        <label>Administrator login</label>
        <div class="tile-subheading center">
            <input type="text" />
        </div>
        <div class="tile-subheading center">
            <input type="text" />
        </div>
        <div class="tile-subheading center">
            <button>Login</button>
        </div>
    </div>
</div>
