<section class="part white">
    <div class="area">
        <h2 class="red-text">Our work</h2>
        <p class="big center margin dark-grey-text">
            Here you can find complete collection of our
            previous projects. For detailed information, simply click any miniature.
        </p>
    </div>
</section>
<section class="part grey grid">
    <?php foreach( $this->reference as $reference ) : ?>
        <a class="leave" href="<?= $this->url('application') ?>work/detail/<?= $reference->id ?>/<?= $this->urlparser( $reference->name ); ?>">
            <div class="third grid-item">
                <div class="text-area">
                    <div class="work-tile">
                        <img src="<?= $reference->img ?>" />
                        <div>
                            <h5><?= $reference->name ?></h5>
                            <p class="small description"><?= $this->date( $reference->time ) ?></p>
                            <p class="medium dark-grey-text"><?= $reference->desc ?></p>
                        </div>
                    </div>
                </div>
            </div>
        </a>
    <?php endforeach; ?>
</section>