<section class="part dark-grey">
    <div class="area">
        <h2 class="left white-text">Admin > Messages</h2>
    </div>    
</section>
<section class="part">
    <?php foreach( $this->messages as $message ) : ?>
        <div class="third">
            <div class="tile">
                <label>messgage #<?php echo $message->id; ?></label>
                <div class="tile-subheading">
                    <p class="small dark-grey-text bold"><?php echo $message->name; ?></p>
                </div>
                <div class="tile-subheading">
                    <p class="small dark-grey-text bold"><?php echo $message->email; ?></p>
                </div>
                <div>
                    <p class="small dark-grey-text"><?php echo $message->text ?></p>
                </div>
                <div class="tile-subheading">
                    <p onClick="ajax( 'messages' , 'delete' , <?php echo $message->id; ?> , $(this).parent().parent().parent() )" class="small dark-grey-text underline"><a>Delete</a></p>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
</section>