<section class="part">
    <div class="third">
        <div class="tile">
            <label>messgage #1</label>
            <div class="tile-subheading">
                <p class="small dark-grey-text bold">Pavel Koch</p>
            </div>
            <div class="tile-subheading">
                <p class="small dark-grey-text bold">kouks.koch@gmail.com</p>
            </div>
            <div>
                <p class="small dark-grey-text">
                    Dolor sit amet, consectetuer adipiscing elit.
                    Nulla pulvinar eleifend sem.
                    Vivamus luctus egestas leo.
                    Aliquam erat volutpat. dolor
                    sit amet, consectetuer adipiscing elit.
                    Nulla pulvinar eleifend sem.
                    Vivamus luctus egestas leo.
                    Aliquam erat volutpat.</p>
            </div>
            <div class="tile-subheading">
                <p class="small dark-grey-text underline"><a>Delete</a></p>
            </div>
        </div>
    </div>
</section>