<?php foreach( $this->post as $post ) { break; } ?>

<section class="part red">
    <div class="area">
        <h2 class="white-text"><?= $post->topic ?></h2>
        <p class="big center margin light-grey-text"><?= $post->desc ?></p>
    </div>
</section>
<section class="part grey">
    <div class="area">
        <div class="text-area">
            <p class="medium dark-grey-text indent margin"><?= $post->text ?></p>
        </div>
    </div>
</section>
<section class="part white">
    <div class="area">
        <div class="text-area">
            <p class="medium dark-grey-text"><?= $post->full_name . " on " . $this->date( $post->time ) ?> | <a class="leave" href="<?php echo $this->url( "application" ); ?>blog">Show all posts</a></p>
        </div>
    </div>
</section>