<section class="part white">
    <div class="area">
        <h2 class="red-text">Sleanded blog</h2>
        <p class="big center text-area dark-grey-text">
            Here we post interesting articles regarding not only IT world.
        </p>
    </div>
</section>
<section class="part grey grid">
    <?php foreach( $this->posts as $post ) : ?>
        <a class="leave" href="<?= $this->url('application') ?>blog/detail/<?= $post->id ?>/<?= $this->urlparser( $post->topic ); ?>">
            <div class="third grid-item">
                <div class="text-area">
                <article class="blog-post">
                    <img src="<?= $this->basePath( $post->img ) ?>" />
                    <div>
                        <h5><?= $post->topic ?></h5>
                        <p class="small description"><?= $post->full_name . " on " .  $this->date( $post->time ) ?></p>
                        <p class="medium dark-grey-text"><?= $post->desc ?></p> 
                    </div>
                </article>
                </div>
            </div>
        </a>
    <?php endforeach; ?>
</section>