<section class="part white">
    <div class="area">
        <h2 class="red-text">Sleanded blog</h2>
        <p class="big center text-area dark-grey-text">
            Here we post interesting articles regarding not only IT world.
        </p>
    </div>
</section>
<section class="part grey grid">
    <?php foreach( $this->posts as $post ) : ?>
        <div class="third grid-item">
            <div class="text-area">
            <article class="blog-post">
                <img src="<?= $post->img ?>" />
                <div>
                    <h5><?= $post->topic ?></h5>
                    <p class="small description"><?= $post->full_name . " on " .  $this->date( $post->time ) ?></p>
                    <p class="medium dark-grey-text"><?= strlen( $post->text ) > 150 ? substr( $post->text , 0 , 150 ) . "..." : $post->text ?></p> 
                </div>
            </article>
            </div>
        </div>
    <?php endforeach; ?>
</section>