<section class="part white">
    <div class="area">
        <h2 class="red-text">Sleanded blog</h2>
        <p class="big center text-area dark-grey-text">
            Here we post interesting articles regarding not only IT world.
        </p>
    </div>
</section>
<section class="part grey grid">
    <div class="third grid-item">
        <div class="text-area">
        <article class="blog-post">
            <img src="http://lorempixel.com/g/640/480/abstract" />
            <div>
                <h5>Lorem ipsum</h5>
                <p class="small description">28. 10. 2015</p>
                <p class="medium dark-grey-text">
                    Dolor sit amet, consectetuer adipiscing elit.
                    Nulla pulvinar eleifend sem.
                    Vivamus luctus egestas leo.
                    Aliquam erat volutpat. dolor
                    sit amet, consectetuer adipiscing elit.
                    Nulla pulvinar eleifend sem.
                    Vivamus luctus egestas leo.
                    Aliquam erat volutpat.
                </p> 
            </div>
        </article>
        </div>
    </div>
    
    <div class="third grid-item">
        <div class="text-area">
        <article class="blog-post">
            <img src="http://lorempixel.com/g/640/480/technics" />
            <div>
                <h5>Lorem ipsum</h5>
                <p class="small description">28. 10. 2015</p>
                <p class="medium dark-grey-text">
                    Dolor sit amet, consectetuer adipiscing elit.
                    Nulla pulvinar eleifend sem.
                    Vivamus luctus egestas leo.
                    Aliquam erat volutpat. dolor
                    sit amet, consectetuer adipiscing elit.
                    Nulla pulvinar eleifend sem.
                    Vivamus luctus egestas leo.
                    Aliquam erat volutpat.
                </p> 
            </div>
        </article>
        </div>
    </div>
    
    <div class="third grid-item">
        <div class="text-area">
        <article class="blog-post">
            <img src="http://lorempixel.com/g/640/480/cats" />
            <div>
                <h5>Lorem ipsum</h5>
                <p class="small description">28. 10. 2015</p>
                <p class="medium dark-grey-text">
                    Dolor sit amet, consectetuer adipiscing elit.
                    Nulla pulvinar eleifend sem.
                    Vivamus luctus egestas leo.
                    Aliquam erat volutpat. dolor
                    sit amet, consectetuer adipiscing elit.
                    Nulla pulvinar eleifend sem.
                    Vivamus luctus egestas leo.
                    Aliquam erat volutpat.
                </p> 
            </div>
        </article>
        </div>
    </div>
    <div class="third grid-item">
        <div class="text-area">
        <article class="blog-post">
            <img src="http://lorempixel.com/g/640/480/abstract" />
            <div>
                <h5>Lorem ipsum</h5>
                <p class="small description">28. 10. 2015</p>
                <p class="medium dark-grey-text">
                    Dolor sit amet, consectetuer adipiscing elit.
                    Nulla pulvinar eleifend sem.
                    Vivamus luctus egestas leo.
                    Aliquam erat volutpat. dolor
                    sit amet, consectetuer adipiscing elit.
                    Nulla pulvinar eleifend sem.
                    Vivamus luctus egestas leo.
                    Aliquam erat volutpat.
                </p> 
            </div>
        </article>
        </div>
    </div>
    
    <div class="third grid-item">
        <div class="text-area">
        <article class="blog-post">
            <img src="http://lorempixel.com/g/640/480/technics" />
            <div>
                <h5>Lorem ipsum</h5>
                <p class="small description">28. 10. 2015</p>
                <p class="medium dark-grey-text">
                    Dolor sit amet, consectetuer adipiscing elit.
                    Nulla pulvinar eleifend sem.
                    Vivamus luctus egestas leo.
                    Aliquam erat volutpat. dolor
                    sit amet, consectetuer adipiscing elit.
                    Nulla pulvinar eleifend sem.
                    Vivamus luctus egestas leo.
                    Aliquam erat volutpat.
                </p> 
            </div>
        </article>
        </div>
    </div>
    
    <div class="third grid-item">
        <div class="text-area">
        <article class="blog-post">
            <img src="http://lorempixel.com/g/640/480/cats" />
            <div>
                <h5>Lorem ipsum</h5>
                <p class="small description">28. 10. 2015</p>
                <p class="medium dark-grey-text">
                    Dolor sit amet, consectetuer adipiscing elit.
                    Nulla pulvinar eleifend sem.
                    Vivamus luctus egestas leo.
                    Aliquam erat volutpat. dolor
                    sit amet, consectetuer adipiscing elit.
                    Nulla pulvinar eleifend sem.
                    Vivamus luctus egestas leo.
                    Aliquam erat volutpat.
                </p> 
            </div>
        </article>
        </div>
    </div>
</section>