<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Sleanded')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/bootstrap.css'))
                        ->prependStylesheet($this->basePath('css/hover.min.css'))
                        ->prependStylesheet($this->basePath('css/skillset.css'))
                        ->prependStylesheet($this->basePath('css/glob.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.js'), 'text/javascript')
            ->prependFile($this->basePath('js/load.js'), 'text/javascript')
            ->prependFile($this->basePath('js/jquery.imageScroll.min.js'), 'text/javascript')
            ->prependFile('http://code.jquery.com/jquery.min.js', 'text/javascript')
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        
        <header class="header">
            <div class="img-header" data-image="img/banner.png" data-width="1900" data-height="1266"></div>
            <div id="top-bar">
                <div id="logo">
                    <img src="img/logo50.png" />
                </div>
                <p class="logo-text">Sleanded</p>
                <nav id="primary">
                    <a>home</a>
                    <a>team</a>
                    <a>our work</a>
                    <a>contact</a>
                    <a>blog</a>
                    <!--<a class="fb"><div class="icon-fb"></div></a>
                    <a class="twitter"><div class="icon-twitter"></div></a>-->
                </nav>
            </div>
            <div id="motto">
                <h1><span class="red">WE</span> LIVE YOUR VISION</h1>
                <p class="motto-text">
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
                    Nulla pulvinar eleifend sem. Vivamus luctus egestas leo.
                    Aliquam erat volutpat.	
                </p>
            </div>
            <div id=buttons>
                <a class="hvr-grow contact">contact us</a>
                <a class="work">our work</a>
            </div>
        </header>
        
        <div id="content">
            <div id="container">
                <?php echo $this->content; ?>
            </div>
        </div>
        
        <footer>
            <div id="bottom-bar"></div>
        </footer>
        
        <!--
        <nav id="side">
            <a class="active">home</a>
            <a>about</a>
            <a>our work</a>
        </nav>
        -->
        
        <?php echo $this->inlineScript() ?>
        
    </body>
</html>
