<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Sleanded')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/hover.min.css'))
                        ->prependStylesheet($this->basePath('css/skillset.css'))
                        ->prependStylesheet($this->basePath('css/glob.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/images.js'), 'text/javascript')
            ->prependFile($this->basePath('js/page.js'), 'text/javascript')
            ->prependFile($this->basePath('js/main.js'), 'text/javascript')
            ->prependFile($this->basePath('js/masonry.pkgd.min.js'), 'text/javascript')
            ->prependFile($this->basePath('js/jquery.imageScroll.min.js'), 'text/javascript')
            ->prependFile($this->basePath('js/jquery.nicescroll.min.js'), 'text/javascript')
            ->prependFile('http://code.jquery.com/jquery.min.js', 'text/javascript')
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>   
        <div class="page">
            <header class="primary">
                <div class="img-header" data-image="img/banner.png" data-width="1900" data-height="1266"></div>
                <div id="fixed-bar"></div>
                <div id="top-bar">
                    <div id="logo">
                        <img height="100%" src="img/logo50.png" />
                    </div>
                    <p class="logo-text-sleanded">Sleanded</p>
                    <p class="logo-text-codes">codes</p>
                    <nav id="primary">
                        <a class="leave" href="<?php echo $this->basePath(""); ?>">home</a>
                        <a class="leave" href="<?php echo $this->basePath("work"); ?>">our work</a>
                        <a class="leave" href="<?php echo $this->basePath("contact"); ?>">contact</a>
                        <a class="leave" href="<?php echo $this->basePath("team"); ?>">team</a>
                        <a class="leave" href="<?php echo $this->basePath("blog"); ?>">blog</a>
                        <!--<a class="fb"><div class="icon-fb"></div></a>
                        <a class="twitter"><div class="icon-twitter"></div></a>-->
                    </nav>
                </div>
                <div id="motto">
                    <h1><span class="red-text">WE</span> LIVE YOUR VISION</h1>
                    <p class="motto-text">
                        We love to start every project from scratch to create pixel-perfect,
                        responsive and innovative websites. 
                        Let us make your vision become reality.
                    </p>
                </div>
                <div id="buttons">
                    <a class="hvr-grow contact">contact us</a>
                    <a class="work">our work</a>
                </div>
            </header>

            <div id="content">
                <?php echo $this->content; ?>
            </div>

            <footer>
                Copyright &copy; Sleanded 2012-2015
            </footer>


            <!--
            <nav id="side">
                <a class="active">home</a>
                <a>about</a>
                <a>our work</a>
            </nav>
            -->

            <?php echo $this->inlineScript() ?>
        </div>
    </body>
</html>
