<section class="part dark-grey">
    <div class="area">
        <h2 class="left white-text">Admin > Users</h2>
    </div>    
</section>
<section class="part">
    <div class="area">
         <?php
         $form = $this->form;
         $form->prepare();
         echo $this->form()->openTag($form);
         ?>
         <?=    $this->formElement( $form->get('name') ) .  
                $this->formElement( $form->get('full_name') ) . 
                $this->formElement( $form->get('email') ) .
                $this->formElement( $form->get('password') ) ?>
        
        POST IN COMPANY -> FB
        
        <?= $this->formButton( $form->get('submit') , "add" ) ?>        
        <?= $this->form()->closeTag() ?>
    </div>
</section>