<section class="part dark-grey">
    <div class="area">
        <h2 class="left white-text">Admin > Users</h2>
    </div>    
</section>
<section class="part">
    <div class="area">
        <h3>List of admins</h3>
        <table class='admin' width='100%'>
            <tr>
                <th class="thin">#</th>
                <th>Name</th>
                <th>Full Name</th>
                <th>E-mail</th>
                <th>Job</th>
                <th>IP</th>
            </tr>
            <?php foreach( $this->users as $u ) : ?>
                <tr>
                    <td> <?= $u->id ?> </td>
                    <td> <?= $u->name ?> </td>
                    <td> <?= $u->full_name ?> </td>
                    <td> <?= $u->email ?> </td>
                    <td> <?= $u->job ?> </td>
                    <td> <?= $u->ip ?> </td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>
</section>