<section class="part dark-grey">
    <div class="area">
        <h2 class="left white-text">Admin > Users</h2>
    </div>    
</section>
<section class="part">
    <div class="area">
        <h3>User panel</h3>
        <table class='table-basic' width='100%'>
            <?php foreach( $this->users as $u ) : ?>
                <tr>
                    <td> <?= $u['name'] ?> </td>
                    <td> <?= $u['full_name'] ?> </td>
                    <td> <?= $u['email'] ?> </td>
                    <td> <?= $u['job'] ?> </td>
                    <td> <?= $u['ip'] ?> </td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>
</section>