<?php echo $this->messenger( $this->message ); ?>

<section class="part dark-grey">
    <div class="area">
        <h2 class="left white-text">Admin > Reference > Add</h2>
    </div>    
</section>
<section class="part">
    <div class="area">
         <?php $form = $this->form;
               $form->prepare();
               $form->setAttribute('class' , 'admin');
               echo $this->form()->openTag($form); ?>
        
         <?=   $this->formElement( $form->get('desc') ) .  
               $this->formElement( $form->get('img') ) . 
               $this->formElement( $form->get('displayed') ) . 
               $this->formButton( $form->get('submit') , 'Save' ) ?>
             
        <?= $this->form()->closeTag() ?>
    </div>
</section>