<section class="part dark-grey">
    <div class="area">
        <h2 class="left white-text">Dashboard</h2>
    </div>    
</section>
<section class="part">
    <div class="half">   
        <h3 class="center dark-grey-text">New messages</h3>
        <table class="admin">
            <tr>
                <th>Name</th>
                <th>Text</th>
            </tr>
            <tr>
                <td>Pavel Koch</td>
                <td>i want website</td>
            </tr>
            <tr>
                <td>Michael Bausano</td>
                <td>me too</td>               
            </tr>            
        </table>
    </div>    
    <div class="half">
        <h3 class="center dark-grey-text">Pending TODOs</h3>
    </div>     
    <div class="half">
        <h3 class="center dark-grey-text">Latest blog posts</h3>
    </div>  
</section>