<section class="part dark-grey">
    <div class="area">
        <h2 class="left white-text">Dashboard</h2>
    </div>    
</section>
<section class="part grid">
    <div class="half grid-item"> 
        <div class="text-area">
            <h3 class="center dark-grey-text">New messages</h3>
            <?php if( count( $this->messages ) > 0 ) : ?>
                <table class="admin">
                    <tr>
                        <th>Name</th>
                        <th>E-mail</th>
                        <th>Text</th>
                    </tr>
                    <?php foreach( $this->messages as $message ) : ?>
                        <tr>  
                            <td><?= $message->name ?></td>
                            <td><?= $message->email ?></td>
                            <td><?= strlen( $message->text ) > 30 ? substr( $message->text , 0 , 30 ) . "..." : $message->text ?></td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            <?php else : ?>
                <h4 class="center dark-grey-text">No new messages :(</h4>
            <?php endif; ?>
        </div>
    </div>    
    <div class="half grid-item">
        <div class="text-area">
            <h3 class="center dark-grey-text">Your tickets</h3>
            <p class="big dark-grey-text">
                - rozlišit zobrazování .area na idnexu a jinde<br />
                - Dodělat form na users<br />
                - Newslettery?<br />
                - Statistiky (ga?)<br />
            </p>
        </div>
    </div>     
    <div class="half grid-item">
        <div class="text-area">
            <h3 class="center dark-grey-text">Latest blog posts</h3>
        </div>
    </div>  
</section>