
<section class="part red">
    <div class="half team-tile" 
         style="background: url('img/napis.png') center center no-repeat #fff; background-size: contain;">
    </div>
    <div class="half team-tile">
        <div class="text-area">
            <h3 class="white-text">Our team</h3>
            <p class="big justify margin indent white-text">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
            </p>
        </div>
    </div>
</section>

<?php foreach( $this->team as $index=>$coder ) : ?>
    <section class="part white">
        <?php if( $index % 2 == 0 ) : ?>
            <div class="half team-tile">
                <div class="text-area">
                    <h4><?= $coder->full_name ?></h4>
                    <p class="medium description"><?= str_replace( ";" , ", " , $coder->job ) ?></p>
                    <p class="big justify margin indent about grey-text">
                        <?= $coder->desc ?>
                    </p>
                </div>
            </div>
            <div class="half no-padding team-tile">
                <img src="<?= $this->basePath( $coder->img ) ?>" />
            </div>
        <?php else : ?>
            <div class="half no-padding team-tile">
                <img src="<?= $this->basePath( $coder->img ) ?>" />
            </div>
            <div class="half team-tile">
                <div class="text-area">
                    <h4><?= $coder->full_name ?></h4>
                    <p class="medium description"><?= str_replace( ";" , ", " , $coder->job ) ?></p>
                    <p class="big justify margin indent about grey-text">
                        <?= $coder->desc ?>
                    </p>
                </div>
            </div>
        <?php endif; ?>
    </section>
<?php endforeach; ?>