
<section class="part red">
    <div class="half no-padding team-tile" 
         style="background: url('img/napis.png') center center no-repeat #fff; background-size: contain;">
    </div>
    <div class="half team-tile">
        <h3 class="white-text">Our team</h3>
        <p class="big justify margin indent white-text">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        </p>
    </div>
</section>

<section class="part white">
    <div class="half team-tile">
        <h4>Michael Bausano</h4>
        <p class="medium description">ceo, coder</p>
        <p class="big justify margin indent about grey-text">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        </p>
    </div>
    <div class="half no-padding team-tile">
        <img src="img/my.png" />
    </div>
</section>

<section class="part white">
    <div class="half no-padding team-tile">
        <img src="img/my.png" />
    </div>
    <div class="half team-tile">
        <h4>Pavel Koch</h4>
        <p class="medium description">ceo, coder, designer</p>
        <p class="big justify margin indent about grey-text">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        </p>
    </div>
</section>