<section class="part red">
    <div class="area">
        <h2 class="white-text">Contact us</h2>
    </div>
</section>
<section class="part white">
    <div class="area">
        <h3 class="red-text">Useful contact information</h3>
        <table class="table-basic" width="100%;">
            <tr>
                <th width="50%">E-mail</th>
                <td>info@sleanded.com</td>
            </tr>
            <tr>
                <th width="50%">Phone</th>
                <td>+420 720 468 227, +420 720 468 227</td>
            </tr>  
            <tr>
                <th width="50%">Identification number</th>
                <td>asdfasdf</td>
            </tr>     
            <tr>
                <th width="50%">Address</th>
                <td>Český Těšín, ČR</td>
            </tr>         
        </table>
    </div>
</section>
<section class="part red">
    <div class="area">
        <h3 class="white-text">Contact us online!</h3>
        <!---->
        
        <form id="contact" action="" method="post">
            <p class="paragraph grey-text">It's easy! Just fill out this form and hit the send button!</p>
            <input placeholder="name" type="text" />
            <input placeholder="e-mail" type="text" />
            <input placeholder="phone" type="text" />
            <select>
                <option selected disabled hidden>Where did you hear of us?</option>
                <option>FB</option>
                <option>FB</option>
                <option>FB</option>
            </select>
            <textarea name="text" placeholder="your message"></textarea>
            <button>Send</button>
        </form>
    </div>
</section>