<section class="part"> 
    <div class="area">
        <h2>Our story</h2>
        
        <p class="justify about">
            dolor
            sit amet, consectetuer adipiscing elit.
            <span class="red">Nulla pulvinar eleifend sem.</span>
            Vivamus luctus egestas leo.
            Aliquam erat volutpat.
            Nulla accumsan, elit sit amet varius semper,
            nulla mauris mollis quam,
            tempor suscipit diam nulla vel leo.
            Maecenas aliquet accumsan leo.
            Lorem ipsum dolor
            sit amet, consectetuer adipiscing elit.
            Nulla pulvinar eleifend sem.
            Vivamus luctus egestas leo.
            Aliquam erat volutpat.
            Nulla accumsan, elit sit amet varius semper,
            nulla mauris mollis quam,
            tempor suscipit diam nulla vel leo.
            Maecenas aliquet accumsan leo.
        </p>
    </div>
</section>


<section id="why-us" class="part">
    <div class="img-why-us" data-image="img/hand.png" data-width="2000" data-height="1000"></div>
    <div class="area">
        <h2>Why choose us</h2>
        
        <p class="justify">
            dolor
            sit amet, consectetuer adipiscing elit.
            Nulla pulvinar eleifend sem.
            Vivamus luctus egestas leo.
            Aliquam erat volutpat.
            Nulla accumsan, elit sit amet varius semper,
            nulla mauris mollis quam,
            tempor suscipit diam nulla vel leo.
            Maecenas aliquet accumsan leo.
            Lorem ipsum dolor
            sit amet, consectetuer adipiscing elit.
            Nulla pulvinar eleifend sem.
            Vivamus luctus egestas leo.
            Aliquam erat volutpat.
            Nulla accumsan, elit sit amet varius semper,
            nulla mauris mollis quam,
            tempor suscipit diam nulla vel leo.
            Maecenas aliquet accumsan leo.
        </p>
        
        <div class="third">
            <div class="skill">
                <figure class="chart" data-percent="100">
                    <figcaption class="html">Teamwork</figcaption>
                    <svg width="200" height="200"> <circle class="outer" cx="95" cy="95" r="85" transform="rotate(-90, 95, 95)"/> </svg>
                </figure>
            </div>
        </div>
        <div class="third">
            <div class="skill">
                <figure class="chart" data-percent="75">
                    <figcaption class="html">Creativity</figcaption>
                    <svg width="200" height="200"> <circle class="outer" cx="95" cy="95" r="85" transform="rotate(-90, 95, 95)"/> </svg>
                </figure>
            </div>
        </div>
        <div class="third">
            <div class="skill">
                <figure class="chart" data-percent="50">
                    <figcaption class="html">Innovation</figcaption>
                    <svg width="200" height="200"> <circle class="outer" cx="95" cy="95" r="85" transform="rotate(-90, 95, 95)"/> </svg>
                </figure>
            </div>
        </div>
    </div>
</section>

<section class="part">
    <div class="area">
        <h2>What have we done so far</h2>
        <div class="reference">
            <img src="img/ref1.png" />
            <h4>Useless website</h4>
            <p class="reference-text">A bunch of useless websites.
                This has no use. Overall it was just a big waste of time.</p>
        </div>
        <div class="reference">
            <img src="img/ref2.png" />
            <h4>Useful website</h4>
            <p class="reference-text">Despite the name, this website is still useless
                as hell. Another waste of time.</p>
        </div>
        <div class="reference">
            <img src="img/ref3.png" />
            <h4>Web templates</h4>
            <p class="reference-text">Our source of inspiration (not really).</p>
        </div>
        
    </div>
</section>

<section id="blog" class="part">
    <div class="img-blog" data-image="img/book.png" data-width="2000" data-height="1000"></div>
    <div class="area">
        <h2>Latest blog posts</h2>
        <article class="post">
            <img src="http://lorempixel.com/g/640/480/abstract/gray" />
            <h5>Lorem ipsum</h5>
            <p class="post-text">dolor
                sit amet, consectetuer adipiscing elit.
                Nulla pulvinar eleifend sem.
                Vivamus luctus egestas leo.
                Aliquam erat volutpat.</p>
        </article>
        <article class="post">
            <img src="http://lorempixel.com/g/640/480/technics/gray" />
            <h5>Lorem ipsum</h5>
            <p class="post-text">dolor
                sit amet, consectetuer adipiscing elit.
                Nulla pulvinar eleifend sem.
                Vivamus luctus egestas leo.
                Aliquam erat volutpat.</p>
        </article>
        <article class="post">
            <img src="http://lorempixel.com/g/640/480/cats/gray" />
            <h5>Lorem ipsum</h5>
            <p class="post-text">dolor
                sit amet, consectetuer adipiscing elit.
                Nulla pulvinar eleifend sem.
                Vivamus luctus egestas leo.
                Aliquam erat volutpat.</p>
        </article>
    </div>
</section>

<section class="part">
    <div class="area">
        <h3>Contact form</h3>
        <form id="contact" action="" method="post">
            <input placeholder="name" type="text" />
            <input placeholder="e-mail" type="text" />
            <input placeholder="phone" type="text" />
            <select>
                <option selected disabled hidden>Where did you hear of us?</option>
                <option>FB</option>
                <option>FB</option>
                <option>FB</option>
            </select>
            <textarea name="text" placeholder="your message"></textarea>
            <button>Send</button>
        </form>
    </div>
</section>