<section class="part white"> 
    <div class="area">
        <h2 class="red-text">Our story</h2>
        <div class="half">
            <p class="justify paragraph">
                <span class="red-text">Sleanded is a brand-new coding company formed by 
                    flexible and creative students who love what they are doing and are good at it.</span>
            </p>
            <p class="justify paragraph dark-grey-text">
                One chilly winter evening, two friends have decided they’d wanted a change
                in their boring lives. So they quit playing Minecraft and got somehow
                excited about making websites. They started off slowly - learnt basic <span class="red-text">HTML</span> and <span class="red-text">CSS</span>.
                However, as time passed by, they wanted to make their websites more interactive
                and add some responsivity, too. That is when they met <span class="red-text">php</span> and <span class="red-text">jQuery</span>.
                Those days, they were no more than fourteen-year-old innocent yordles. 
            <p class="justify paragraph dark-grey-text">
                They went beyond creating websites, those handy students also
                learnt how to create desktop and browser applications in <span class="red-text">Java</span> or <span class="red-text">C++</span>.
            </p>
            <p class="justify paragraph dark-grey-text">
                Nowadays, they have mastered many techniques of creating stunning websites,
                useful apps and user-friendly interfaces.
            </p>
            <p class="justify paragraph dark-grey-text">
                Behold, <span class="red-text">Sleanded</span>!
            </p>
        </div>
        <div class="half">
            <div class="progress-bar" data-percent="92%">
                <div><label>HTML</label></div>    
            </div>
            <div class="progress-bar" data-percent="87%">
                <div><label>CSS</label></div>
            </div>
            <div class="progress-bar" data-percent="95%">
                <div><label>php</label></div>
            </div>
            <div class="progress-bar" data-percent="84%">
                <div><label>jQuery</label></div>
            </div>
            <div class="progress-bar" data-percent="65%">
                <div><label>Java</label></div>
            </div>
            <div class="progress-bar" data-percent="60%">
                <div><label>C++</label></div>
            </div>
        </div>
    </div>
</section>


<section id="why-us" class="part">
    <div class="img-why-us" data-image="img/hand.png" data-width="2000" data-height="1000"></div>
    <div  class="area">
        <h2 class="red-text">Why choose us</h2>
        
        <p class="justify paragraph grey-text">
            Since we are a company with fresh and young team,
            our idea box is filled with crative solutions.
            We believe that, despite huge competition on this market,
            we will make our way through it and bring something new! 
        </p>
        <p class="justify paragraph grey-text">
            As has been mentioned before, we are a starting company
            thus all projects are dealth with swiftly and are carefully tailored to client’s requests.
            All of this for very pleasant prices because we are building up our reference portfolio!
        </p>
        <p class="justify paragraph">
            <a class="leave" href="<?php echo $this->basePath("team"); ?>"><span class="red-text">Meet our team!</span></a>
        </p>
        <!--
        <div class="third">
            <div class="skill">
                <figure class="chart" data-percent="100">
                    <figcaption class="html">Teamwork</figcaption>
                    <svg width="200" height="200"> <circle class="outer" cx="95" cy="95" r="85" transform="rotate(-90, 95, 95)"/> </svg>
                </figure>
            </div>
        </div>
        <div class="third">
            <div class="skill">
                <figure class="chart" data-percent="75">
                    <figcaption class="html">Creativity</figcaption>
                    <svg width="200" height="200"> <circle class="outer" cx="95" cy="95" r="85" transform="rotate(-90, 95, 95)"/> </svg>
                </figure>
            </div>
        </div>
        <div class="third">
            <div class="skill">
                <figure class="chart" data-percent="50">
                    <figcaption class="html">Innovation</figcaption>
                    <svg width="200" height="200"> <circle class="outer" cx="95" cy="95" r="85" transform="rotate(-90, 95, 95)"/> </svg>
                </figure>
            </div>
        </div>
        -->
    </div>
</section>

<section class="part white">
    <div class="area">
        <h2 class="red-text">Our recent projects</h2>
        <div class="reference">
            <img src="img/ref1.png" />
            <h4>Useless website</h4>
            <p class="reference-text dark-grey-text">A bunch of useless websites.
                This has no use. Overall it was just a big waste of time.</p>
        </div>
        <div class="reference">
            <img src="img/ref2.png" />
            <h4>Useful website</h4>
            <p class="reference-text dark-grey-text">Despite the name, this website is still useless
                as hell. Another waste of time.</p>
        </div>
        <div class="reference">
            <img src="img/ref3.png" />
            <h4>Web templates</h4>
            <p class="reference-text dark-grey-text">Our source of inspiration (not really).</p>
        </div>
    </div>
</section>

<section id="blog" class="part">
    <div class="img-blog" data-image="img/book.png" data-width="2000" data-height="1000"></div>
    <div class="area">
        <h2 class="red-text">Latest blog posts</h2>
        <article class="post">
            <img src="http://lorempixel.com/g/640/480/abstract/gray" />
            <h5>Lorem ipsum</h5>
            <p class="post-text grey-text">dolor
                sit amet, consectetuer adipiscing elit.
                Nulla pulvinar eleifend sem.
                Vivamus luctus egestas leo.
                Aliquam erat volutpat.</p>
        </article>
        <article class="post">
            <img src="http://lorempixel.com/g/640/480/technics/gray" />
            <h5>Lorem ipsum</h5>
            <p class="post-text grey-text">dolor
                sit amet, consectetuer adipiscing elit.
                Nulla pulvinar eleifend sem.
                Vivamus luctus egestas leo.
                Aliquam erat volutpat.</p>
        </article>
        <article class="post">
            <img src="http://lorempixel.com/g/640/480/cats/gray" />
            <h5>Lorem ipsum</h5>
            <p class="post-text grey-text">dolor
                sit amet, consectetuer adipiscing elit.
                Nulla pulvinar eleifend sem.
                Vivamus luctus egestas leo.
                Aliquam erat volutpat.</p>
        </article>
    </div>
</section>

<section class="part red">
    <div class="area">
        <h2 class="white-text">Contact form</h2>
        <form id="contact" action="" method="post">
            <input placeholder="name" type="text" />
            <input placeholder="e-mail" type="text" />
            <input placeholder="phone" type="text" />
            <select>
                <option selected disabled hidden>Where did you hear of us?</option>
                <option>FB</option>
                <option>FB</option>
                <option>FB</option>
            </select>
            <textarea name="text" placeholder="your message"></textarea>
            <button>Send</button>
        </form>
    </div>
</section>