<div class="part">
    <div class="area">
        <h2>Who we are</h2>
        <section>
            <div class="third">
                <h3>Lorem ipsum</h3>
                <p>
                    dolor
                    sit amet, consectetuer adipiscing elit.
                    Nulla pulvinar eleifend sem.
                    Vivamus luctus egestas leo.
                    Aliquam erat volutpat.
                    Nulla accumsan, elit sit amet varius semper,
                    nulla mauris mollis quam,
                    tempor suscipit diam nulla vel leo.
                    Maecenas aliquet accumsan leo.
                </p>
            </div>
            <div class="third">
                <h3>Lorem ipsum</h3>
                <p>
                    dolor
                    sit amet, consectetuer adipiscing elit.
                    Nulla pulvinar eleifend sem.
                    Vivamus luctus egestas leo.
                    Aliquam erat volutpat.
                    Nulla accumsan, elit sit amet varius semper,
                    nulla mauris mollis quam,
                    tempor suscipit diam nulla vel leo.
                    Maecenas aliquet accumsan leo.
                </p>
            </div>
            <div class="third">
                <h3>Lorem ipsum</h3>
                <p>
                    dolor
                    sit amet, consectetuer adipiscing elit.
                    Nulla pulvinar eleifend sem.
                    Vivamus luctus egestas leo.
                    Aliquam erat volutpat.
                    Nulla accumsan, elit sit amet varius semper,
                    nulla mauris mollis quam,
                    tempor suscipit diam nulla vel leo.
                    Maecenas aliquet accumsan leo.
                </p>
            </div>
        </section>
    </div>
</div>
<div id="home-img" data-image="img/deska.png" data-width="2000" data-height="721"></div>
<div style="margin-top: 300px;" class="part">
    <div class="area">
        <h2>Our previous work</h2>
    </div>
</div>