<section class="part grey">
    <div class="area">
        
        <h2>Our work</h2>
        <div class="reference">
            <img src="img/ref1.png" />
            <h4>Useless website</h4>
            <p class="reference-text dark-grey-text">A bunch of useless websites.
                This has no use. Overall it was just a big waste of time.</p>
        </div>
        <div class="reference">
            <img src="img/ref2.png" />
            <h4>Useful website</h4>
            <p class="reference-text dark-grey-text">Despite the name, this website is still useless
                as hell. Another waste of time.</p>
        </div>
        <div class="reference">
            <img src="img/ref3.png" />
            <h4>Web templates</h4>
            <p class="reference-text dark-grey-text">Our source of inspiration (not really).</p>
        </div>
        <div class="reference">
            <img src="img/ref1.png" />
            <h4>Useless website</h4>
            <p class="reference-text dark-grey-text">A bunch of useless websites.
                This has no use. Overall it was just a big waste of time.</p>
        </div>
        <div class="reference">
            <img src="img/ref2.png" />
            <h4>Useful website</h4>
            <p class="reference-text dark-grey-text">Despite the name, this website is still useless
                as hell. Another waste of time.</p>
        </div>
        <div class="reference">
            <img src="img/ref3.png" />
            <h4>Web templates</h4>
            <p class="reference-text dark-grey-text">Our source of inspiration (not really).</p>
        </div>
        <div class="reference">
            <img src="img/ref1.png" />
            <h4>Useless website</h4>
            <p class="reference-text dark-grey-text">A bunch of useless websites.
                This has no use. Overall it was just a big waste of time.</p>
        </div>
        <div class="reference">
            <img src="img/ref2.png" />
            <h4>Useful website</h4>
            <p class="reference-text dark-grey-text">Despite the name, this website is still useless
                as hell. Another waste of time.</p>
        </div>
        <div class="reference">
            <img src="img/ref3.png" />
            <h4>Web templates</h4>
            <p class="reference-text dark-grey-text">Our source of inspiration (not really).</p>
        </div>
</section>