<section class="part grey">
    <div class="area">
        
        <h2 class="red-text">Our work</h2>
        <p class="big center margin dark-grey-text">Here you can find complete collection of our previous projects. You can get detailed information by clicking the miniature.</p>
        <div class="reference">
            <img src="img/ref1.png" />
            <div>
                <h4>Useless website</h4>
                <p class="medium description">28. 10. 2015</p>
                <p class="medium dark-grey-text">A bunch of useless websites.
                    This has no use. Overall it was just a big waste of time.</p>
            </div>
        </div>
        <div class="reference">
            <img src="img/ref2.png" />
            <div>
                <h4>Useful website</h4>
                <p class="medium description">28. 10. 2015</p>
                <p class="medium dark-grey-text">Despite the name, this website is still useless
                    as hell. Another waste of time.</p>
            </div>
        </div>
        <div class="reference">
            <img src="img/ref3.png" />
            <div>
                <h4>Web templates</h4>
                <p class="medium description">28. 10. 2015</p>
                <p class="medium dark-grey-text">Our source of inspiration (not really).</p>
            </div>
        </div>
        <div class="reference">
            <img src="img/ref3.png" />
            <div>
                <h4>Web templates</h4>
                <p class="medium description">28. 10. 2015</p>
                <p class="medium dark-grey-text">Our source of inspiration (not really).</p>
            </div>
        </div>
        <div class="reference">
            <img src="img/ref1.png" />
            <div>
                <h4>Useless website</h4>
                <p class="medium description">28. 10. 2015</p>
                <p class="medium dark-grey-text">A bunch of useless websites.
                    This has no use. Overall it was just a big waste of time.</p>
            </div>
        </div>
        <div class="reference">
            <img src="img/ref2.png" />
            <div>
                <h4>Useful website</h4>
                <p class="medium description">28. 10. 2015</p>
                <p class="medium dark-grey-text">Despite the name, this website is still useless
                    as hell. Another waste of time.</p>
            </div>
        </div>
        <div class="reference">
            <img src="img/ref1.png" />
            <div>
                <h4>Useless website</h4>
                <p class="medium description">28. 10. 2015</p>
                <p class="medium dark-grey-text">A bunch of useless websites.
                    This has no use. Overall it was just a big waste of time.</p>
            </div>
        </div>
        <div class="reference">
            <img src="img/ref2.png" />
            <div>
                <h4>Useful website</h4>
                <p class="medium description">28. 10. 2015</p>
                <p class="medium dark-grey-text">Despite the name, this website is still useless
                    as hell. Another waste of time.</p>
            </div>
        </div>
        <div class="reference">
            <img src="img/ref3.png" />
            <div>
                <h4>Web templates</h4>
                <p class="medium description">28. 10. 2015</p>
                <p class="medium dark-grey-text">Our source of inspiration (not really).</p>
            </div>
        </div>
</section>