<?= $this->messenger( $this->message ); ?>
<?php foreach( $this->project as $project ) { break; } ?>


<section class="part dark-grey">
    <div class="area">
        <h2 class="left white-text">Admin > Projects > View</h2>
    </div>    
</section>

<section class="part">
    <div class="area">
        <h3>Project: <?= $project->name ?></h3>
        <h4>Project info</h4>
        <hr />
        <p class="big dark-grey-text margin"><?= $project->desc ?></p>
        <h4>Progress</h4>
        <hr />
        <div class="progress-bar stripped" data-percent="60%">
            <div><label>Creating label</label></div>    
        </div>
        <h4>Tickets</h4>
        <hr />

    </div>
</section>
<script>
    $("tr").click( function() {
        if( ( href = $(this).data("href") ) !== '' ) {
            location.href = href;
        }
    });
</script>